apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deployment
  labels: 
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template: 
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: avian19/nginx-ne:latest-1.0
        ports:
        - containerPort: 80
