apiVersion: v1
kind: Service
metadata: 
  name: backend-service
spec:
  selector:
    app: school
    tier: backend
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
  type: NodePort
